= BigTable TestContainer

This module is all about providing a convenient testcontainer for bigtable. Fortunately, Google provides a Google Cloud SDK implementation for a BigTable (in-memory) emulator, and a Docker image for running Google Cloud SDK commands.

== Usage

To deploy the container for a specific tests, one can use the following snippet.

NOTE: The below snippet will spin up a single container for the whole test class, if you want to spin of a new container for each test method, simply define the container as a field variable of your test class. (Still annotated with `@Container`)

[source,kotlin]
----
@Testcontainers
internal class BigTableContainerTest {

    companion object {
        @Container private val bigTable = BigTableContainer()
    }

    ...
}
----

== License

....
Copyright 2021 DataLbry.io

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
....
